[2025-01-30T23:57:23.244+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T23:57:23.271+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_airflow_roles.get_owners manual__2025-01-30T23:57:22.460856+00:00 [queued]>
[2025-01-30T23:57:23.286+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_airflow_roles.get_owners manual__2025-01-30T23:57:22.460856+00:00 [queued]>
[2025-01-30T23:57:23.286+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T23:57:23.305+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_owners> on 2025-01-30 23:57:22.460856+00:00
[2025-01-30T23:57:23.314+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=425) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T23:57:23.316+0000] {standard_task_runner.py:72} INFO - Started process 428 to run task
[2025-01-30T23:57:23.317+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'manage_***_roles', 'get_owners', 'manual__2025-01-30T23:57:22.460856+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp4h02r3p9']
[2025-01-30T23:57:23.318+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask get_owners
[2025-01-30T23:57:23.380+0000] {task_command.py:467} INFO - Running <TaskInstance: manage_airflow_roles.get_owners manual__2025-01-30T23:57:22.460856+00:00 [running]> on host 512f7139f01a
[2025-01-30T23:57:23.502+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='manage_***_roles' AIRFLOW_CTX_TASK_ID='get_owners' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T23:57:22.460856+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T23:57:22.460856+00:00'
[2025-01-30T23:57:23.504+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T23:57:23.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/***/dags
[2025-01-30T23:57:23.534+0000] {python.py:240} INFO - Done. Returned value was: ['data-team']
[2025-01-30T23:57:23.603+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T23:57:23.605+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=manage_***_roles, task_id=get_owners, run_id=manual__2025-01-30T23:57:22.460856+00:00, execution_date=20250130T235722, start_date=20250130T235723, end_date=20250130T235723
[2025-01-30T23:57:23.653+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T23:57:23.682+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T23:57:23.683+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
